version: '3'
services:
    pdf-to-text:
        env_file:
        - .env
        container_name: pdf-to-text
        build:
            context: .
        ports:
            - "8000:80"
        volumes:
            - ./app:/code/app